### ISSUE TITLE
Anforderungsmanagement

### ISSUE THREAD

**Issue by suchja** [gustda/TTT-Challenge#1]
Ich finde deinen Ansatz die Challenge für dich spannender zu machen sehr gut. Vielleicht überlegst du nochmals ob du das Ziel für deine Challenge etwas konkreter fassen kannst.

Was ganz genau verstehst du unter Anforderungsmanagement und was willst du dabei in dieser Challenge genau üben? Wenn es um das AnforderungsMANAGEMENT geht, dann ist GitHub vielleicht nicht die passende Plattform. Grundsätzlich könntest du zwar deine Anforderungen als Issues erstellen, aber wirklich Anforderungsmanagement ist wohl eher nicht.

Ist natürlich nur mein Input ;-)!

PS: Freue mich sehr, dass du dabei bist!

**Comment by gustda** [comment]
Es sind eher zwei Themen.
1. Möchte ich Github als Versionsverwaltung testen.
2. Möchte ich mit Anforderungen spielen, diese Verwalten und Prioriesieren, weiter entwickeln. Dafür ist das hier möglw. nicht die richtige Plattform. Im ersten Schritt werde ich die im Projekt mit führen, evtl. steige ich auf ein anderes Tool um, wenn sich mein Fokus ändert. Github werde ich mindestens beruflich wohl nicht so bald dafür verwenden. Da ist mein Ziel eher zu gucken, wie sich Anforderungen weiter Entwickeln, wie man diese hin bekommt, dass man selbst den Fokus behält und das produziert, was man gerade braucht und nicht bis überübermorgen vorplant und wie das nicht dazu führen muss, dass man die Arbeit dann doch doppelt macht oder eben doch.
Außerdem möchte ich zum beispiel gucken, wie gut oder schlecht anforderungen von einer auf die andere Lösung übertragbar sind, also von Konsole auf Gui.
1. ist ein eher akademischer Ansatz und verlangt glaub ich ein bisschen selbstdiziplin, da das ganze ja doch recht über schaubar ist.

**Comment by suchja** [comment]
Deinen Ansatz finde ich super! Bezüglich Verwaltung und Planung von Anforderungen könnten dich vielleicht [Episode 1](https://github.com/LernMoment/DailyGitHub/blob/master/ShowNotes.md#semantik-für-labels--episode-1) und [Episode 8](https://github.com/LernMoment/DailyGitHub/blob/master/ShowNotes.md#einführung-milestones--episode-8) der DailyGitHub-Show interessieren. Außerdem könnte ich mir gut vorstellen, dass du in großen Projekten wie beispielsweise [Docker](https://github.com/docker/docker) oder in Projekten rund um [Microsoft .NET](https://github.com/dotnet) hier auf GitHub ein wenig Inspiration findest wie Anforderungen mit GitHub oder auch ganz allgemein realisiert werden.

Bezüglich der beruflichen Relevanz von GitHub bin ich selber noch zu keinem finalen Ergebnis gekommen. Allerdings sehe ich GitHub in vielen Bereichen als extrem wichtig an. So kann es sein, dass sich eine Firma entscheidet zwar nicht ihr Produkt öffentlich auf GitHub zu hosten, aber doch vielleicht einige Bestandteile oder wenigstens Beispiele (siehe [#DailyGitHub-Show Episode 7](https://github.com/LernMoment/DailyGitHub/blob/master/ShowNotes.md#dein-projekt-sinelaborert--episode-7)).
Auch bin ich der Ansicht das GitHub extrem wichtig ist für Networking, Lernen und Üben sowie für Selbstvermarktung. Das alles sind Punkte an die Softwareentwickler (du ausgeschlossen ;) häufig nicht denken. Noch sehr unfertige Gedanken zu diesem Thema habe ich [hier](https://github.com/LernMoment/DailyGitHub/issues?q=is%3Aissue+is%3Aopen+label%3A%22Bereich%3A+These%22) aufgeschrieben. Vielleicht hast du ja Lust deine Erkenntnisse und Meinungen mit mir dort zu teilen.

Meiner Meinung nach lohnt es sich so oder so auf GitHub aktiv zu sein und es als Form der Weiterbildung zu benutzen. Daher bist du aus meiner Sicht auf einem prima Weg.

**Comment by suchja** [comment]
Ich schließe das Issue mal, weil ich mich vom eigentlichen Thema recht weit entferne und du dein Ziel scheinbar klar vor Augen hast.
