### ISSUE TITLE
 Aufgabe #4 Heute -> Design Tag

### ISSUE THREAD

**Issue by gustda** [gustda/TTT-Challenge#6]
Leider habe ich es nicht sooo gut geschafft am Ball zu bleiben, aber mein Ziel, vielleicht in den nächsten zwei Wochen mit meiner Aufgabe durch kommen, so vor dem Urlaub, nun gut dann tue ich heute mal was dafür.

Heute soll es darum gehen fest zulegen was ich von meinem Bisherigen Code weiter verwenden kann und was ich nciht weiter verwenden möchte oder Was kommt in eine Bibliothek um in anderen Projekten verwendet zu werden und was einfach in der Konsolenanwendung verbleibt.

Wie in dem Design Dokument zu sehen ist, habe ich eine MVC (Model View Controler) Architektur gewählt.
Was definitiv mit in die Bibliothek sollte und auch entsprechend vorgesehen war ist das Model, in meinem Fall ist das die Klasse Game und die Koordinaten.

Etwas anders sieht es mit dem GameController aus. Dieser besitzt zum einen logik, die durchaus Wiederverwendbar ist, aber eben auch Code für die Konsole.
Lösung ich werde die Funktion Run(), was die Ausführungsschleife der Anwendung darstellt in die Main auslagern und die Spiellogic im Gamecontroller lassen. Dieser Funktioniert aktuell über Textkommandos, aber im anbetracht der Tatsache, dass die Anwendung nicht so komplex ist, werde ich das dabei belassen, auch mit einer Oberflächen Technologie kann man das verwenden, dann müssen eben die Texte als Parameter mit gegeben werden und nicht ausgelesen werden.

Entschluss steht fest.
GameController entschlacken und in die Bib
Game in die Bib
Coordinate in die Bib
Definitions in die Bib

Und nun, ist der weg so in Ordnung? Irgendwelche Einwände? Ist der Weg nachvollziehbar?

**Comment by suchja** [comment]
Bin mir beim `GameController` nicht sicher. Kann ich dir sagen, wenn ich das Resultat sehe 😜 

Einfach mal machen und schauen wie das Resultat aussieht. Deine Überlegungen zum Design finde ich schon mal sehr gut und auch nachvollziehbar.
