### ISSUE TITLE
Aufgabe #5 Umbau mit Bibliothek

### ISSUE THREAD

**Issue by gustda** [gustda/TTT-Challenge#7]
Heute habe ich die Anpassungen aus #6  umgesetzt.

Der Controler und die Modelklassen sind in eine Bibliothek gewandert, die Konselenanwendung wurde entsprechend umgebaut. 
Die Anwendung verhält sich wie vorher.

**Comment by suchja** [comment]
Woher weißt du, dass sich die Anwendung wie vorher verhält?

**Comment by gustda** [comment]
Ich habe da eine Horde unglaublich erfahrener Tester einen vollständigen Rekursionstest machen lassen. Sprich ich hab das durchgetestet, nach dem die Unittests durchgelaufen sind, hab ich von Hand das Verhalten geprüft und das Verhalt ist wie vorher.

**Comment by suchja** [comment]
Kann ich mir die Horde bei Gelegenheit mal ausleihen? Ich muss da auch noch einiges testen 😉 
Nicht, dass es sich für diese Anwendung lohnen würde, aber verwendest du üblicherweise eine Art Testdokumentation? Für die Unittests nicht, aber für die sonstigen Regressionstest wäre das wohl ganz hilfreich.
