### ISSUE TITLE
Aufgabe #6 Einbau einer Anwendung mit GUI

### ISSUE THREAD

**Issue by gustda** [gustda/TTT-Challenge#8]
Aufgabe heute ist es, eine Anwendung mit GUI zu bauen, die diese Bibliothek verwendet.

Dazu werde ich eine WinForms Anwendung verwenden und ebenfalls in die Projektmappe bauen. Die Steuerung soll durch Bottons erfolgen.
Mehr in den Anforderungen.
Ziel fertig bis zum Endspiel ;-)

**Comment by gustda** [comment]
Gerade noch so geschafft.
Spiel ist lauffähig, aber irgendwie ist das noch nicht schön, also als nächstes erstaml ein Codereview.

**Comment by suchja** [comment]
Wie machst du das Codereview?
